---

- name: ensure acme directory exists
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    mode: 0775
    state: directory
  with_items:
    - "/opt/letsencrypt"
    - "/opt/letsencrypt/.well-known/acme-challenge"
  become: true

- name: copy local certificate shell script
  copy:
    src: "local-certificate.sh"
    dest: "/opt/letsencrypt/local-certificate.sh"
    owner: "{{ ansible_user }}"
    mode: 0777
  become: true

- name: create local certificate
  command: sh /opt/letsencrypt/local-certificate.sh
  args:
    creates: "/opt/letsencrypt/localhost.crt"
  ignore_errors: True
  when: "'velocorner.local' in inventory_hostname"

- name: aws inventory check
  debug:
    msg: inventory is {{ inventory_hostname }}
  when: "'velocorner.com' in inventory_hostname"

- name: install nginx
  yum:
    name: nginx
    state: present
  become: true

- name: set httpd_can_network_connect flag on
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  become: true

- name: deploy reverse proxy setup
  template:
    src: reverse-proxy.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: true
  become: true
