---
- name: install letsencrypt
  yum:
    name: letsencrypt
    state: present
  become: true

- name: ensure acme directory exists
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    mode: 0775
    state: directory
  with_items:
    - "/opt/letsencrypt"
    - "/opt/letsencrypt/.well-known/acme-challenge"
  become: true

- name: create facme challenge file
  copy:
    dest: "/opt/letsencrypt/.well-known/acme-challenge/test.txt"
    content: |
      test
  become: true

- name: install nginx
  yum:
    name: nginx
    state: present
  become: true

- name: set httpd_can_network_connect flag on
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  become: true

- name: deploy reverse proxy setup
  template:
    src: reverse-proxy.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: true
  become: true
