- name: install epel packages
  yum:
    name: epel-release
    state: present
  become: true

- name: install base packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - httpd-tools
    - python2-pip
    - vim
    - wget
  become: true
