---
- name: add Kubernetes' YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
  become: true

- name: install kubernetes dependencies
  yum:
    name: ['kubectl']
    state: present
  become: true

- name: install minikube - one node deployment
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube
  become: true

- name: minikube version
  shell: minikube version
  register: minikube_version

- name: print minikube version
  debug:
    var: minikube_version.stdout_lines

- name: start minikube
  shell: /usr/local/bin/minikube start --vm-driver={{ minikube_driver }}
  become: true


