---
- name: "velocorner.local"
  box-image: "generic-x64/centos9s"
  # appears also in the ansible/inventory/local/hosts
  ip: "192.168.0.11"
  reserved_ports: [80,443,7000,8000,9000]
  # AWS T2.small has 2048 only, local is set to 4096 to experiment with k8s
  max-ram: 4096
