---
- name: Ensure plugin directory exists
  file:
    path: "/opt/velocorner"
    owner: "{{ ansible_user }}"
    mode: 0775
    state: directory
  become: true

- name: copy docker compose template
  template:
    src: velocorner-compose.yml.j2
    dest: /opt/velocorner/velocorner-compose.yml
  become: true

- name: deploy velocorner stack
  shell: "docker stack deploy --prune --compose-file /opt/velocorner/velocorner-compose.yml velocorner"
  become: true
