---
- name: copy docker compose template
  template:
    src: velocorner-compose.yml.j2
    dest: /opt/velocorner-compose.yml
  become: true

- name: deploy velocorner stack
  shell: "docker stack deploy --prune --compose-file /opt/velocorner-compose.yml velocorner"
  become: true
