- name: install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: present
  become: true

- name: install lvm2
  yum:
    name: lvm2
    state: present
  become: true

- name: add docker-{{docker_edition}} repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-{{docker_edition}}.repo
    dest: /etc/yum.repos.d/docker-{{docker_edition}}.repo
  become: yes

- name: enable docker {{docker_edition}} repo
  ini_file:
    dest: /etc/yum.repos.d/docker-{{docker_edition}}.repo
    section: 'docker-{{docker_edition}}-{{docker_channel}}'
    option: enabled
    value: 0
  become: yes

- name: enable docker test repo
  ini_file:
    dest: /etc/yum.repos.d/docker-{{docker_edition}}.repo
    section: 'docker-{{docker_edition}}-test'
    option: enabled
    value: 0
  become: yes

- name: install docker-{{docker_edition}}
  yum:
    name: docker-{{docker_edition}}
    state: present
  become: true

- name: start docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: add user {{ansible_user}} to docker group
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes
  become: yes