---
- name: encrypt admin password
  shell: "htpasswd -nb -B admin {{ lookup('env', 'ADMIN_PASSWORD') }} | cut -d ':' -f 2"
  changed_when: false
  register: admin_password_enc

- name: "deploy portainer to {{ inventory_hostname }}"
  docker_container:
    name: portainer
    image: "portainer/portainer-ce:2.14.0"
    state: started
    detach: true
    recreate: false
    pull: yes
    restart_policy: always
    published_ports: "7000:9000"
    container_default_behavior: compatibility
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: "-H unix:///var/run/docker.sock --admin-password '{{ admin_password_enc.stdout }}' --logo https://peregin-static.s3.amazonaws.com/logo100.png"
  register: portainer_docker
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

#- name: Print all available facts
#  ansible.builtin.debug:
#    var: portainer_docker

- name: "setting running status fact"
  set_fact:
    portainer_is_running: "{{ portainer_docker.container.State.Running }}"

- name: "setting portainer ip address fact"
  set_fact:
    portainer_endpoint: "http://{{ portainer_docker.container.NetworkSettings.IPAddress }}:7000/api"

- name: print portainer endpoint
  debug:
    msg: "portainer running:{{ portainer_is_running }}, endpoint: {{ portainer_endpoint }}"